#!/bin/sh

function do_groonga(){
  db=$1
  cmd=$2
  echo "--------------------------------------------------------"
  echo "$cmd"
  echo "--------------------------------------------------------"
  echo ""
  if [ -f $db ] ; then 
    opts=""
  else
    opts="-n"
  fi
  #echo "groonga $opts $db "
  if type jq > /dev/null 2>&1 ; then
    echo "$cmd" | groonga $opts $db | jq .
  else
    echo "$cmd" | groonga $opts $db
  fi
}

